# Generated by Django 5.1.6 on 2025-03-05 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin1',
            fields=[
                ('Admin_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Admin_Name', models.CharField(max_length=25)),
                ('Admin_password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('User_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=16)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone_Number', models.IntegerField()),
                ('Email', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='diseas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseas1', models.CharField(max_length=50)),
                ('medicine1', models.CharField(max_length=50)),
                ('medicine2', models.CharField(max_length=50)),
                ('medicine3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('med_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('med_Name', models.CharField(max_length=30)),
                ('Available_quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mfg_Date', models.DateField()),
                ('Exp_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.IntegerField()),
                ('User_Name', models.CharField(max_length=30)),
                ('Phone_Number', models.IntegerField()),
                ('Date', models.DateField(default=datetime.date.today)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicines_names', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
