# Generated by Django 5.1.6 on 2025-03-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseas',
            name='medicine1',
        ),
        migrations.RemoveField(
            model_name='diseas',
            name='medicine2',
        ),
        migrations.RemoveField(
            model_name='diseas',
            name='medicine3',
        ),
        migrations.AddField(
            model_name='diseas',
            name='medicines',
            field=models.CharField(default='No medicine prescribed', max_length=100),
        ),
    ]
